<?php

namespace GestionBundle\Repository;

/**
 * AbonnementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementsRepository extends \Doctrine\ORM\EntityRepository
{
}
