<?php

namespace GestionBundle\Repository;

/**
 * TrajetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetsRepository extends \Doctrine\ORM\EntityRepository
{
}
